export type Flashcard = { question: string; answer: string };
export type FlashcardReviewStatus = 'known' | 'unknown';
export type ClassSession = {
  date: string;
  topics: string;
  instructor?: string;
  club?: string;
  completed?: boolean;
  notes: string;
  flashcards: Flashcard[];
};
export type Todo = { text: string; done: boolean; dueDate: string };
export type FlightChecklistItem = { id: string; label: string; checked: boolean };
export type FlightChecklistTemplateItem = { id: string; text: string };
export type FlightChecklistTemplateSection = { id: string; title: string; items: FlightChecklistTemplateItem[] };
export type FlightChecklistTemplate = {
  id: string;
  aircraft: string;
  title: string;
  category: 'normal' | 'emergency';
  source: string;
  revisionDate: string;
  sections: FlightChecklistTemplateSection[];
};
export type FlightScheduleEntry = { id: string; date: string; aircraft: string; instructor: string; focus: string; notes: string; completed: boolean };
export type FlightTrainingData = {
  checklist: FlightChecklistItem[];
  outsideChecks: FlightChecklistItem[];
  checklistLibrary: FlightChecklistTemplate[];
  schedule: FlightScheduleEntry[];
  panelPractice: {
    throttle: number;
    mixture: number;
    flaps: number;
    heading: number;
    altitude: number;
    airspeed: number;
    masterOn: boolean;
    avionicsOn: boolean;
    fuelPumpOn: boolean;
  };
};
export type RoadmapMilestoneProgress = {
  completed?: boolean;
  completedDate?: string;
  hours?: number;
  notes?: string;
};
export type GroundSchoolUser = {
  id: string;
  firstName: string;
  role: 'admin' | 'student';
  passwordHash?: string;
  requiresPasswordReset?: boolean;
  homeAirport?: string;
  airportSetupRequired?: boolean;
  dashboardStatOrder?: string[];
  dashboardTileOrder?: string[];
  dashboardHiddenTiles?: string[];
  roadmapProgress?: Record<string, RoadmapMilestoneProgress>;
  roadmapTouchedPhases?: string[];
  classes: ClassSession[];
  todos: Todo[];
  flashcardProgress: Record<string, FlashcardReviewStatus>;
  tcHistory: TcHistoryEntry[];
  tcMissedIds: string[];
  rocaHistory?: TcHistoryEntry[];
  rocaMissedIds?: string[];
  rocaFlashcardSection?: string;
  flightTraining?: FlightTrainingData;
};
export type TcHistoryEntry = {
  title?: string;
  source?: string;
  score?: number;
  total?: number;
  percent: number;
  date?: string;
  completedAt?: string;
  missed?: string[];
};
export type GroundSchoolData = {
  activeUserId: string;
  users: Record<string, GroundSchoolUser>;
  classes: ClassSession[];
  todos: Todo[];
  tcHistory: TcHistoryEntry[];
  tcMissedIds: string[];
  tcFlashcardSection: string;
  rocaHistory: TcHistoryEntry[];
  rocaMissedIds: string[];
  rocaFlashcardSection: string;
  dashboardStatOrder: string[];
  dashboardTileOrder: string[];
  dashboardHiddenTiles: string[];
  roadmapProgress: Record<string, RoadmapMilestoneProgress>;
  roadmapTouchedPhases: string[];
  flashcardProgress: Record<string, FlashcardReviewStatus>;
  flightTraining: FlightTrainingData;
};
export type ViewId = 'dashboard' | 'notes' | 'flashcards' | 'tasks' | 'testing' | 'pstar' | 'roca' | 'weather' | 'flightChecklist' | 'flightPanel' | 'outsideChecks' | 'flightSchedule' | 'import' | 'dashboardEdit' | 'users' | 'account';
export type PracticeQuestion = { id: string; section: string; q: string; options: string[]; correct: string };
export type PstarQuestion = PracticeQuestion;
